### ISSUE TITLE
allowing response to be handled normally when session times out

### ISSUE THREAD

**Issue by yogthos** [ring-clojure/ring-session-timeout#1]
The current implementation seems to conflate session timeout with response handling. I think it would be better to make `timeout-response` an optional parameter and allow the response to be handled normally when it's not specified:

``` clojure
(defn wrap-idle-session-timeout
  "Middleware that times out idle sessions after a specified number of seconds.

  If a session is timed out, the timeout-response option is returned. This is
  usually a redirect to the login page.

  The following options are accepted:

  :timeout          - the idle timeout in seconds (default 600 seconds)
  :timeout-response - the response to send if an idle timeout occurs"
  {:arglists '([handler options])}
  [handler {:keys [timeout timeout-response] :or {timeout 600}}]
  {:pre [(integer? timeout) (or (nil? timeout-response) (map? timeout-response))]}
  (fn [request]
    (let [session  (:session request {})
          end-time (::idle-timeout session)
          timeout? (and end-time (< end-time (current-time)))]      
      (cond
        (and timeout? timeout-response)
        (assoc timeout-response :session nil)

        timeout?
        (assoc (handler (dissoc request :session)) :session nil)

        :else
        (let [response (handler request)
              end-time (+ (current-time) timeout)
              session  (-> (:session response session)
                           (assoc ::idle-timeout end-time))]
          (assoc response :session session))))))
```

**Comment by weavejester** [comment]
I considered making `timeout-response` optional, but it made the middleware logic more complex, and I couldn't figure out a use case where it would be useful.

Presumably you have a particular scenario in mind? Could you provide an example of where this would be used?

**Comment by gered** [comment]
Sometimes its just more convenient to let the request continue as-is after the session times out, so keeping the response returned from `handler` (just without `:session`) works better.

Maybe you have a few different sections of an app that handle lack of session info differently ... e.g. authentication-required routes redirect to a login when the session is lost, or some unauthenticated parts of the web app don't need to do that and don't care so much if the session is lost

I don't really think this complicates things that much. The middleware function above is still quite small and readable in my opinion.

To be honest though, I'm kind of thinking `timeout-response` should probably be a function that returns a response instead of a map. Offers the most flexibility (e.g. at work, I have some apps where I like to log something when a user's session expires... in addition to redirecting to an idle timeout page, makes some support calls easier to track what happened for clueless users) and the code would still look fairly similar.

**Comment by weavejester** [comment]
Why would you add timeout middleware to parts of the website that don't care if the session is lost? Why not just limit the timeout middleware to the parts that do care about sessions?

The problem with omitting a redirect is that you run into problems with things like cookie-based sessions. In order to remove a session you need to return a response, so if you don't have some form of timeout-response, you place the handler into a situation where they have no valid session, and cannot set any session data.

Usually any handler with the `wrap-session` middleware will always have a valid session. It might be blank, but the session can be read and written to. If we omit a timeout response, the handler has to deal with a new scenario: a missing `:session` key.

On the other hand, if we force a timeout-response, the handler can always assume that it has a valid session. This seems a more reliable option in general.

Is there anything I haven't considered? Is there a scenario where you'd want to time out the session, but also want to execute the handler without a valid session?

**Comment by gered** [comment]
Unless I'm missing something (and maybe I am), if I have a web app which has some routes which don't care so much if the session is lost and are happy enough to just recreate the (usually very very small) bits that they set in the session, and then other routes which _do_ care if the session is lost and want to redirect, then I don't have a choice in using the middleware? If I want it in some places, I need to include it for all. I would have to split up the app into two apps, unless I've missed something somewhere.

You make a good point about cookie-based session, but to be honest, the scenario I'm thinking about is where the app is setting very very trivial bits of practically "throw-away" info in the session in those routes. I will concede that this is not very clean however, and certainly not what you want in anything mission-critical.

> If we omit a timeout response, the handler has to deal with a new scenario: a missing :session key.

Exactly what I would want. Typically in the apps I work on, the routes are able to sensibly handle this scenario and redirect appropriately. Note that these handlers in this case will typically be doing a redirect only (and maybe a bit of logging output, sometimes).

To be honest, there may very well be a better way to handle this, but I think having the same timeout-response for an entire app is not _always_ the best solution. Certainly not in my experience.

**Comment by weavejester** [comment]
> I would have to split up the app into two apps?

Middleware can be applied selectively. You don't need to apply middleware to your entire application. You can apply it to a very small area.

Ring generally encourages selective application of middleware. It's a simpler solution than trying to build exceptions into middleware that's always applied globally.

> the scenario I'm thinking about is where the app is setting very very trivial bits of practically "throw-away" info in the session in those routes.

This middleware is designed to expire sessions ASAP for security purposes. The session store manages eventual expiry for the purposes of reducing space.

I'm having a hard time understanding what sort of information would be trivial and throwaway, yet at the same time need to be expired within a strict time limit. Surely any sessions that require strict security would be important by definition?

**Comment by yogthos** [comment]
My feeling is that this arbitrarily restricts the workflow. The case where `timeout-response` is supplied remains exactly the same in both scenarios. While the cases described might not fit your workflow, I don't see why you'd feel strongly about other people having to adjust theirs to fit it.

The session itself will be expired regardless of where the response is handled, but it can be useful to have the ability to generate a contextual response based on where it was routed. The current approach prevents that.

Finally, as I mentioned originally the design conflates two distinct actions. Timing out the session is not inherently tied to the response handling in any way.

**Comment by weavejester** [comment]
In order to expire the session, you need to return a response. You provide a workaround to this where you execute the handler in a sessionless state, then expire the session after the handler completes.

The problem I have with this idea is that it changes how the handler interacts with the session. You've expired the session, but haven't provided the handler with a new session. Instead you have this strange zombie state where the old session is effectively dead, but the new session has yet to be created.

Maybe this is necessary, but I'd like someone to give me a use-case for this first.

**Comment by yogthos** [comment]
I have a couple of use cases in mind. First, would be when a client session expires on a specific page and when the session is recreated we'd like to return it to that page. This is a fairly common scenario for things like stores.

When the expiry middleware simply expires the session and allows the request to bubble up, other middleware or handlers can then apply the appropriate logic down the chain. However, when you mix the concerns of expiry and response handling this is no longer possible.

Another example is how restricted routes work in lib-noir. The middleware allows the user to supply functions associated with URI patterns that can be used to decide whether the URI should be accessible. It's common for the decision function to check the user in the session and route based on that.

This, again, requires that the expiry middleware to allow the request to bubble up further the chain so that it can be handled by the restricted routes middleware.

The idea is that you should have the flexibility to handle the absence of a session by using separate application specific middleware.

On a side note, is there a reason why this shouldn't be part of ring-core middleware. Unless I'm missing something, without expiry the session store will grow indefinitely, so it seems like a critical piece of middleware to me that prevents memory leaks.

**Comment by weavejester** [comment]
> First, would be when a client session expires on a specific page and when the session is recreated we'd like to return it to that page.

That's a reasonable use-case. It could be solved with a `:timeout-handler` option, though.

> However, when you mix the concerns of expiry and response handling this is no longer possible.

Well, expiry _is_ response handling. You need to return a response to expire the session. There's no avoiding that. It's only a case of whether you make the connection explicit or not.

This isn't a question of separating concerns, but whether we should try to hide a connection that already exists.

> Another example is how restricted routes work in lib-noir. The middleware allows the user to supply functions associated with URI patterns that can be used to decide whether the URI should be accessible. It's common for the decision function to check the user in the session and route based on that.
> 
> This, again, requires that the expiry middleware to allow the request to bubble up further the chain so that it can be handled by the restricted routes middleware.

I don't see how the solution you outline would solve this. Let's say the user POSTs with an expired session. The handler at the bottom needs to know, then and there, whether the POST is allowed, so that it can choose whether or not to commit it to the database. It can't ask for the opinion of middleware higher up the stack, not without some form of continuation.

> On a side note, is there a reason why this shouldn't be part of ring-core middleware.

It may be eventually. The advantage of putting it in a separate library is that we can experiment without holding up the main Ring releases. Another advantage is that we can break the API in a 0.1.0 release, but in a 1.0.0+ release, everything needs to be backward compatible.

The majority of new functionality of Ring will start life as separate libraries like ring-session-timeout. After it reaches 1.0.0 status, then we can consider whether or not to merge it into Ring itself.

> Unless I'm missing something, without expiry the session store will grow indefinitely, so it seems like a critical piece of middleware to me that prevents memory leaks.

This middleware can't prevent memory leaks. If a user visits your site once, and then never returns, then the expiry part of this middleware will never be called. This middleware is designed to prevent expired sessions from getting to the handler, it isn't to clean up expired sessions from the database.

It's the job of the session store itself to expire sessions for the purposes of keeping storage space low. No other part of the system can have this job, because the mechanisms for expiry differ depending on the storage engine used. Something like Redis can expire keys by itself, while something like Postgres might need a background thread or process that runs hourly.

**Comment by yogthos** [comment]
I think that a timeout handler would be a nice solution, then either a timeout-response or timeout-handler are specified depending on the situation. Ideally, the handler would accept the handler and the request and be able to decide what to do in that situation.

> Well, expiry is response handling. You need to return a response to expire the session. There's no avoiding that. It's only a case of whether you make the connection explicit or not.

Right, I'm not arguing that however, what I'm saying is that the act of clearing the session and generating a response based on whether a session exists or not are separate tasks. The response generation part of expiry can often be application specific. Forcing it to be a static value is rather limiting.

> I don't see how the solution you outline would solve this. Let's say the user POSTs with an expired session. The handler at the bottom needs to know, then and there, whether the POST is allowed, so that it can choose whether or not to commit it to the database. It can't ask for the opinion of middleware higher up the stack, not without some form of continuation.

Middleware wrapped by the session expiry can handle the request before it's routed to the handler. In fact, this is precisely the use case I have with [wrap-restricted](https://github.com/noir-clojure/lib-noir/blob/master/src/noir/util/route.clj#L31) middleware in lib-noir. I would like to clear the session and then use the wrap-restricted middleware to handle the empty session.

I see your point regarding memory leaks, you would need an active process for guaranteeing that inactive sessions are cleared.

**Comment by weavejester** [comment]
Okay, I think I see where you're coming from. You envision the `wrap-restricted` middleware to be _inside_ the session timeout middleware.

It's possible that I could remove any logic that deals with session expiry, or make it optional in the cases where a `:timeout-response` is not set. The handler could then check the session-timeout keys on the session directly, e.g.

``` clojure
(defn handler [request]
  (if (session-idle-expiry? request)
    timeout-response
    normal-response))
```

Where `session-idle-expiry?` would be an included function in `ring.middleware.session-timeout`:

``` clojure
(defn session-idle-expiry? [request]
  (if-let [timeout (-> request :session ::idle-timeout)]
    (< timeout (current-time))))
```

**Comment by yogthos** [comment]
Glad to see we're on the same page here. I think the solution you've outlined sounds like the most elegant way to address this. I would keep the default behaviour when the `:timeout-response`  is set since it is likely to be the common case.

**Comment by frankiesardo** [comment]
What are your thoughts on json vs html expired sessions?

For html requests it makes sense to redirect to a login, but for the JS that is currently running on the application we'd like to return a 401. Would you add a different middleware depending on the content-type? Does `:timeout-handler` make more sense in this case?

**Comment by weavejester** [comment]
This should be fixed by the `:timeout-handler` option added by #3.

**Comment by erjoalgo** [comment]
I came to this discussion because one my GET requests from javascript got a login redirect with HTML contents instead of the JSON content type it was expecting. I don't see that I have explicitly included session-timeout.

Is it possible that this session-timeout middleware is included indirectly via some other middleware? I am using this middleware based on a luminus webapp template:

```
(defn wrap-base [handler]
  (-> ((:middleware defaults) handler)
      wrap-flash
      (wrap-session {:cookie-attrs {:http-only true}})
      (wrap-defaults
       (-> site-defaults
           (assoc-in [:security :anti-forgery] false)
           (dissoc :session)))
      wrap-internal-error))
```

How can I determine why my :session key is nil?

**Comment by weavejester** [comment]
The code sample you provided doesn't appear contain the session timeout middleware, unless it's added by `wrap-internal-error`. You could try checking your dependency tree with `lein deps :tree` or `clj -X:deps tree` and see if this middleware has been added.

You do have some weirdness in your code as well. The `wrap-defaults` middleware adds the flash and session middleware, so you don't need to add those explicitly. It's strange that you'd tell `wrap-defaults` not to add the session, only to then add the session anyway. Why not just let `wrap-defaults` do it?

There may also be issues with your code. It may be that you're accidentally removing the session, but that's just speculation as I can't see your code. In any case, your issue is likely unrelated to `wrap-session-timeout`.

**Comment by erjoalgo** [comment]
My code comes directly from the [luminus](https://luminusweb.com/) default new app template: `lein new luminus app`:

```
(ns app.middleware
  (:require
    [app.env :refer [defaults]]
    [clojure.tools.logging :as log]
    [app.layout :refer [error-page]]
    [ring.middleware.anti-forgery :refer [wrap-anti-forgery]]
    [app.middleware.formats :as formats]
    [muuntaja.middleware :refer [wrap-format wrap-params]]
    [app.config :refer [env]]
    [ring.middleware.flash :refer [wrap-flash]]
    [ring.adapter.undertow.middleware.session :refer [wrap-session]]
    [ring.middleware.defaults :refer [site-defaults wrap-defaults]])
  )

(defn wrap-internal-error [handler]
  (let [error-result (fn [^Throwable t]
                       (log/error t (.getMessage t))
                       (error-page {:status 500
                                    :title "Something very bad has happened!"
                                    :message "We've dispatched a team of highly trained gnomes to take care of the problem."}))]
    (fn wrap-internal-error-fn
      ([req respond _]
       (handler req respond #(respond (error-result %))))
      ([req]
       (try
         (handler req)
         (catch Throwable t
           (error-result t)))))))

(defn wrap-csrf [handler]
  (wrap-anti-forgery
    handler
    {:error-response
     (error-page
       {:status 403
        :title "Invalid anti-forgery token"})}))


(defn wrap-formats [handler]
  (let [wrapped (-> handler wrap-params (wrap-format formats/instance))]
    (fn
      ([request]
         ;; disable wrap-formats for websockets
         ;; since they're not compatible with this middleware
       ((if (:websocket? request) handler wrapped) request))
      ([request respond raise]
       ((if (:websocket? request) handler wrapped) request respond raise)))))

(defn wrap-base [handler]
  (-> ((:middleware defaults) handler)
      wrap-flash
      (wrap-session {:cookie-attrs {:http-only true}})
      (wrap-defaults
        (-> site-defaults
            (assoc-in [:security :anti-forgery] false)
            (dissoc :session)))
      wrap-internal-error))
```

Maybe some collaboration should happen to address what you think is weird.

From my read of the `ring.middleware.session` docs, it seems like the only way to delete the session would be for a handler to explicitly include `:session nil` in the response map?

I've checked the dep tree, I don't see session-timeout but looking at relevant deps, I do see `luminus/ring-ttl-session`, which seems to expire the session. This probably answers my query.

```
   [metosin/reitit-middleware "0.5.18"]
   [org.ring-clojure/ring-websocket-middleware "0.2.1"]
   [luminus/ring-ttl-session "0.3.3"]
```
